/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "flume_constants.h"

const flumeConstants g_flume_constants;

flumeConstants::flumeConstants() {}
