/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "flume_constants.h"



const flumeConstants g_flume_constants;

flumeConstants::flumeConstants() {
}



