#!/bin/bash

if [ -z $HUSKY_ROOT ]; then
  export HUSKY_ROOT=/PATH/TO/HUSKY
fi
export HUSKY_BUILD=$HUSKY_ROOT/release

g++ $@ -std=c++14 -DWITH_HDFS -DWITH_MONGODB -I$HUSKY_ROOT -lzmq -lhdfs3 -lmongoclient -pthread -ltcmalloc -lboost_system -lboost_filesystem -L$HUSKY_BUILD -lhusky
